name: tool
publish_to: none
environment:
  sdk: '>3.0.0'
dependencies:
  args: ^2.7.0
  charcode: ^1.1.3
  glob: ^2.1.3
  image: ^4.6.0
  markdown: ^7.3.0
  mime_type: ^1.0.1
  mustache_template: ^2.0.2
  path: ^1.7.0
  pool: ^1.4.0
  sass: ^1.26.5
  shelf: ^1.4.2
  string_scanner: ^1.0.5
